sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ASD1234ko
  redis:
    host: 192.168.122.1
    port: 6379
    database: 1
    password: ASD1234ko
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tCN2fHC5UY9omFBJC3S
    access-key-secret: gjtpmCAtQxPJ5l20NI93Q60AVCxOKc
    bucket-name: sky-tak-out
  wechat:
    appid: wx839c792db136734a
    secret: a94604c057da316f1ee730a90d82051a
    mchid : 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php
  shop:
    address: 湖南省长沙市高新区东方红中路368号
  baidu:
    ak: VjZ1T3j1lrGDTGkfGalwlEZjAH46iGDG
